server:
  port: 8888
  
spring:  datasource:    url: jdbc:mysql:// 192.168.206.1:3306/ssm?characterEncoding=utf8&serverTimezone=UTC&allowMultiQueries=true
    username: root
    password: MISSYOU123
  resources: 
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:c:/upload/  profiles:    active: dev  ##  那个配置文件

mybatis:  mapper-locations: classpath:mybatis/mapper/*.xml  type-aliases-package: com.luoliang.entity
  
logging:  level:    com.luoliang.mapper: debug
    
fdfs:
  so-timeout: 1500
  connect-timeout: 600
  tracker-list:
  - 192.168.244.66:22122
  thumb-image:
    width: 200
    height: 200
    
   
    
